version: '3'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5401:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: sportparken
      POSTGRES_USER: sportparken

  web:
    build: ./web
    ports:
      - "8113:80"
    links:
      - database:database
    environment:
      DB_NAME: sportparken
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "sportparken.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
