version: '3'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5401:5432"
    environment:
      POSTGRES_DB: sportparken
      POSTGRES_USER: sportparken
      POSTGRES_PASSWORD: insecure

  web:
    build: ./web
    ports:
      - "8113:8000"
    links:
      - database
    environment:
      DATABASE_NAME: sportparken
      DATABASE_USER: sportparken
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "sportparken.wsgi:application"
      UWSGI_PROCESSES: 4
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/sportparken/static=/static"
