# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 23:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huurder',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('kvk', models.CharField(max_length=10, null=True)),
                ('sport', models.CharField(max_length=64, null=True)),
                ('bezoek_adres', models.CharField(max_length=255, null=True)),
                ('post_adres', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'huurders',
            },
        ),
        migrations.CreateModel(
            name='HuurderObjectRelation',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('huurder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_set', to='sportparken.Huurder')),
            ],
            options={
                'db_table': 'huurder_object_relaties',
            },
        ),
        migrations.CreateModel(
            name='Ondergrond',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'ondergrond_type',
            },
        ),
        migrations.CreateModel(
            name='Sportpark',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'sportparken',
            },
        ),
        migrations.CreateModel(
            name='SportparkGeometry',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('bron', models.TextField(null=True)),
                ('sportpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_geometry_set', to='sportparken.Sportpark')),
            ],
            options={
                'db_table': 'geometry_sportparken',
            },
        ),
        migrations.CreateModel(
            name='SportparkObject',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('objectType', models.CharField(max_length=164, null=True)),
                ('verhuurprijs', models.FloatField(null=True)),
                ('sportpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportparkobject_set', to='sportparken.Sportpark')),
            ],
            options={
                'db_table': 'sportpark_objecten',
            },
        ),
        migrations.CreateModel(
            name='SportparkObjectGeometry',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('bron', models.CharField(max_length=64, null=True)),
                ('lokaalid', models.CharField(max_length=38, null=True)),
                ('veld_id', models.CharField(max_length=13, null=True)),
                ('bagpndid', models.CharField(max_length=20, null=True)),
                ('ondergrond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_geometry_set', to='sportparken.Ondergrond')),
                ('sportparkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_geometry_set', to='sportparken.SportparkObject')),
            ],
            options={
                'db_table': 'geometry_sportpark_objecten',
            },
        ),
        migrations.AddField(
            model_name='huurderobjectrelation',
            name='sportpark_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_set', to='sportparken.SportparkObject'),
        ),
    ]
