# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportparken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportparkgeometry',
            name='bron',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sportparkobjectgeometry',
            name='bagpndid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sportparkobjectgeometry',
            name='bron',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sportparkobjectgeometry',
            name='lokaalid',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='sportparkobjectgeometry',
            name='veld_id',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='huurder',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sportpark',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
