# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportparken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportparkgeometry',
            name='sportpark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportparken.Sportpark'),
        ),
    ]
