# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportparken', '0003_auto_20170630_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huurder',
            name='bezoek_adres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='huurder',
            name='post_adres',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
