# -*- coding: utf-8 -*-
# Generated by Datapunt on 2017-11-24 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportparken', '0005_sportparkobject_soort_omschrijving'),
    ]

    operations = [
        migrations.RunSQL(
            f"""
                -- remove duplicate geometry field from Schellingerwoude
                DELETE FROM geometry_sportparken WHERE tid=8;
                -- move comments from name field to omschrijving
                UPDATE public.sportpark_objecten 
                  SET omschrijving=
                    CASE 
                      WHEN substring(name,'[A-Za-z]\s[\d+\sA-Z]*(.*)') = '' THEN null
                      ELSE substring(name,'[A-Za-z]\s[\d+\sA-Z]*(.*)') 
                    END;
                -- keep only numbers and letters like 10A
                UPDATE public.sportpark_objecten
                SET name=replace(substring(name,'\d+[\sA-Z]*'),' ','')
            """)
    ]