# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huurder',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'huurders',
            },
        ),
        migrations.CreateModel(
            name='HuurderObjectRelation',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('huurder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_set', to='sportparken.Huurder')),
            ],
            options={
                'db_table': 'huurder_object_relaties',
            },
        ),
        migrations.CreateModel(
            name='Sportpark',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'sportparken',
            },
        ),
        migrations.CreateModel(
            name='SportparkGeometry',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('sportpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_geometry_set', to='sportparken.Sportpark')),
            ],
            options={
                'db_table': 'geometry_sportparken',
            },
        ),
        migrations.CreateModel(
            name='SportparkObject',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
                ('objectType', models.CharField(max_length=164, null=True)),
                ('sportpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportparkobject_set', to='sportparken.Sportpark')),
            ],
            options={
                'db_table': 'sportpark_objecten',
            },
        ),
        migrations.CreateModel(
            name='SportparkObjectGeometry',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('objectOndergrond', models.CharField(max_length=164, null=True)),
                ('sportparkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_geometry_set', to='sportparken.SportparkObject')),
            ],
            options={
                'db_table': 'geometry_sportpark_objecten',
            },
        ),
        migrations.AddField(
            model_name='huurderobjectrelation',
            name='sportpark_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ho_set', to='sportparken.SportparkObject'),
        ),
    ]
