# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportparken', '0002_huurder_kvk'),
    ]

    operations = [
        migrations.AddField(
            model_name='huurder',
            name='sport',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
